version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sjce123
      MYSQL_DATABASE: college_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql:/docker-entrypoint-initdb.d/data.sql

  web:
    build: .
    container_name: college-flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:sjce123@sql-db:3306/college_db

volumes:
  db_data: